// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"context"

	"github.com/test/valid-project/internal/dao/internal"
)

// helloDao is the data access object for table hello.
// You can define custom methods on it to extend its functionality as needed.
type helloDao struct {
	*internal.HelloDao
}

var (
	// Hello is a globally accessible object for table hello operations.
	Hello = helloDao{internal.NewHelloDao()}
}

// CountByStatus counts records by status using a local result struct.
// The local struct should not trigger CODE-DAO-001.
func (d *helloDao) CountByStatus(ctx context.Context, status string) (int, error) {
	type Result struct {
		Count int
	}
	var result Result
	_ = result
	return 0, nil
}
