// Copyright GoFrame gf Author(https://goframe.org). All Rights Reserved.
//
// This Source Code Form is subject to the terms of the MIT License.
// If a copy of the MIT was not distributed with this file,
// You can obtain one at https://github.com/gogf/gf.

// rules_gen.go checks that auto-generated files in model/do, model/entity,
// and dao/ directories contain the "DO NOT EDIT" protection header,
// preventing manual modifications that would be overwritten by code generation.

package check

import (
	"context"
	"strings"
)

// generatedFileDirs maps directory paths that should contain generated files
// to the rule ID and description for checking.
var generatedFileDirs = []struct {
	dir      string
	ruleID   string
	message  string
}{
	{"internal/model/do", "GEN-001", "Files in internal/model/do/ are auto-generated and should have a 'DO NOT EDIT' header"},
	{"internal/model/entity", "GEN-002", "Files in internal/model/entity/ are auto-generated and should have a 'DO NOT EDIT' header"},
	{"internal/dao/internal", "GEN-003", "Files in internal/dao/internal/ (generated by gf gen dao) should have a 'DO NOT EDIT' header"},
}

// GeneratedFileRule checks that auto-generated files have protection headers.
type GeneratedFileRule struct {
	BaseRule
}

// NewGeneratedFileRule creates a new GeneratedFileRule.
func NewGeneratedFileRule() *GeneratedFileRule {
	return &GeneratedFileRule{
		BaseRule: BaseRule{
			RuleID:          "GEN",
			RuleName:        "Generated File Protection",
			RuleDescription: "Checks that auto-generated files contain 'DO NOT EDIT' headers",
			RuleSeverity:    SeverityWarning,
		},
	}
}

// Run executes generated file protection checks against the project.
func (r *GeneratedFileRule) Run(_ context.Context, project *Project) []*Violation {
	var violations []*Violation

	for _, genDir := range generatedFileDirs {
		// Check both single-repo and mono-repo paths.
		dirsToCheck := []string{genDir.dir}

		// For mono-repo, also check app/{service}/internal/...
		if project.IsMono {
			for dir := range project.Dirs {
				if hasPrefix(dir, "app/") {
					parts := splitPath(dir)
					if len(parts) >= 2 {
						dirsToCheck = append(dirsToCheck, "app/"+parts[1]+"/"+genDir.dir)
					}
				}
			}
		}

		for _, checkDir := range dirsToCheck {
			violations = append(violations, r.checkDir(project, checkDir, genDir.ruleID, genDir.message)...)
		}
	}

	return violations
}

// checkDir checks all Go files in a directory for the DO NOT EDIT header.
func (r *GeneratedFileRule) checkDir(project *Project, dir, ruleID, message string) []*Violation {
	var violations []*Violation

	files := project.FilesInDirRecursive(dir)
	for _, f := range files {
		// Skip non-generated files (only check .go files that have content).
		if f.Content == "" || f.ParseErr != nil {
			continue
		}
		// Check for "DO NOT EDIT" marker in the first 10 lines.
		if !containsDoNotEdit(f.Content) {
			violations = append(violations, &Violation{
				RuleID:     ruleID,
				Severity:   SeverityWarning,
				Message:    f.Path + " is in a generated directory but lacks a 'DO NOT EDIT' header",
				FilePath:   f.Path,
				Suggestion: "Add '// Code generated by GoFrame CLI tool. DO NOT EDIT.' at the top of the file, or move it out of the generated directory",
			})
		}
	}

	return violations
}

// containsDoNotEdit checks if the content contains "DO NOT EDIT" within the first 10 lines.
func containsDoNotEdit(content string) bool {
	lines := strings.Split(content, "\n")
	limit := 10
	if len(lines) < limit {
		limit = len(lines)
	}
	for i := 0; i < limit; i++ {
		if strings.Contains(lines[i], "DO NOT EDIT") {
			return true
		}
	}
	return false
}
